### ISSUE TITLE
Feature 1: User can search for cards in a database 

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now search for cards by name and submit search.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to look up any Magic: The Gathering card by its name.  There will be an area for the user to input their search and a button to submit said input.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/192332865-b1bfd883-9a67-4741-a8f9-6d448320bcc9.png)

![image](https://user-images.githubusercontent.com/106715675/192332989-33e8ccef-76fe-48a5-bd15-48cd4dd02219.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Build HTML for home screen
- [x] Add form for search bar
- [x] Style elements as needed
- [x] Ensure that the search is returning data from the API
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
