### ISSUE TITLE
Feature 2: User can see results of their search

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see the result of their search.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After searching for a card, a picture of a card will appear along with relevant information to the card
(name, mana cost, type, flavor text, artist, etc.)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/192334893-20672af5-85ac-4881-b5cd-702bdf59ed6e.png)

![image](https://user-images.githubusercontent.com/106715675/192334639-224a294b-ab05-4ca5-ad46-f6efd61d9032.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create sister div element to the home page for view swapping
- [x] Create nav bar with anchor tag that leads back to the search view
- [x] Create image element that gets populated with data from API request when search is submitted.
- [x] Create div elements for card name, mana cost, flavor text, artist, etc. that are populated with data from the API request, also when search is submitted.
- [x] Style with CSS as necessary
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
