### ISSUE TITLE
Feature 3: User can save cards to a deck

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their favorite cards to a separate deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There will be an icon that can be selected on the search results screen. When selected that card will be saved to a deck that holds all of the users favorited cards.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/192335549-a1274e72-8bbb-4155-8ace-8f2ed0957038.png)

![image](https://user-images.githubusercontent.com/106715675/192335599-24b4f32c-5243-45ce-b74a-753796e01caf.png)

![image](https://user-images.githubusercontent.com/106715675/192335711-b6b9060e-f7be-480a-b844-838081678ae1.png)

![image](https://user-images.githubusercontent.com/106715675/192335752-56be7c3f-b4bb-4aac-803b-92f6432b4758.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add in a sister span element that holds a star icon outline
- [x] When the star icon is clicked, it should fill in the outline
- [x] Create a data model to store saved cards into, The data model should have an array that stores the card as an object.  Each favorited card will also have a unique CardID.
- [x] Create an event listener that will add the favorited cards information into the data model when the star is clicked on.
- [x] Create an event listener that will save the data model with all of the favorited card data into local storage
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
