### ISSUE TITLE
Feature 4: User can see deck of favorited cards

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see a compiled deck of all cards that they have favorited

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A button will be added so that users can access their deck.  Users will be able to view the cards that they have favorited while performing their searches.  The cards will appear as just an image at first, but if the user wants to see more info on the card they only need to click on the card and the info will appear.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/192336473-9cbea007-6fa1-4d37-9b9d-0ac6928d378c.png)

![image](https://user-images.githubusercontent.com/106715675/192336510-4c748eb6-3d6c-4c39-a97b-4360da4331fe.png)

![image](https://user-images.githubusercontent.com/106715675/192336545-8bb0bb06-686e-44a3-a08b-e54546b1145b.png)

![image](https://user-images.githubusercontent.com/106715675/192336932-1f62f70c-9c1c-4191-b53a-e5f19aedaf0f.png)

![image](https://user-images.githubusercontent.com/106715675/192336985-1fe13b90-3df0-4da9-9bba-41a6ad3c3ceb.png)

![image](https://user-images.githubusercontent.com/106715675/192337020-19cebb95-f1e5-4c4e-a321-3f0dbaa1134f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create new anchor tag for nav bar
- [x] When anchor tag is clicked, switch views to favorited cards
- [x] Create dummy data to represent what the view should look like. (This dummy data should just be the image of the favorited card)
- [x] Write a renderElements function to build DOM elements dynamically
- [x] Add event listener for when user clicks on the image of the card
- [x] When User clicks on card, modal should appear with image of card along with other relevant information on the card
- [x] Give user ability to close modal by clicking
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
