### ISSUE TITLE
Feature 5: User can delete cards from their favorited deck

### ISSUE THREAD

**Issue by mdoanle** [mdoanle/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now choose to remove cards from their favorited deck.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A delete button will now be available.  If the delete button is selected that card will be removed from the user's favorited list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/106715675/192338080-8c971b69-ba1f-4a9d-8bde-53831a01e796.png)

![image](https://user-images.githubusercontent.com/106715675/192338113-12931b37-f313-4e32-becd-75556bb5f486.png)

![image](https://user-images.githubusercontent.com/106715675/192338152-49b14252-5b6d-4d7a-8686-a1d4c1941ca9.png)

![image](https://user-images.githubusercontent.com/106715675/192338187-d00f1d3c-fcec-40d7-9cdb-fe426bad0fa2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add delete button to modal pop-up
- [x] Add event listener for delete button
- [x] On delete button click, remove the card data in the modal from the data model
- [x] Remove deleted card from DOM tree as well.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
